// Code generated by goctl. DO NOT EDIT.
package types

type UserRequest struct {
	ID int64 `path:"id"`
}

type UserReply struct {
	ID      int64   `json:"id"`
	Name    string  `json:"name"`
	Balance float64 `json:"balance"`
}

type UserOrdersRequest struct {
	ID int64 `path:"id"`
}

type UserOrdersReply struct {
	ID       string `json:"id"`
	State    uint32 `json:"state"`
	CreateAt string `json:"create_at"`
}

type OrderRequest struct {
	ID string `path:"id"`
}

type OrderReply struct {
	ID       string `json:"id"`
	State    uint32 `json:"state"`
	CreateAt string `json:"create_at"`
}

type OrderCreateRequest struct {
	ProductID int64 `json:"product_id"`
}

type OrderCreateReply struct {
	Code int `json:"code"`
}

type ProductRequest struct {
	ID int64 `path:"id"`
}

type ProductReply struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Count int64   `json:"count"`
}
